# -*- coding: utf-8 -*-
"""port_scanner.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xLIr5q8_-yUT6809dGsaLlmkxxZvd6Sb
"""



import socket

# Target host
target = input("Enter the target IP or hostname: ")

# Port range
start_port = 1
end_port = 1024

print(f"\nScanning {target} from port {start_port} to {end_port}...\n")

for port in range(start_port, end_port + 1):
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.settimeout(0.5)

    result = sock.connect_ex((target, port))
    if result == 0:
        print(f"Port {port} is OPEN")

    sock.close()